### PR TITLE
Expose frequency in build_dcp script

### PR DESCRIPTION
**Pull request by russell-horvath**
This PR exposes the desired frequency as a command line argument to the `aws_build_dcp_from_cl.sh` script. The defaults are set by the env script generated by golden gate and overwritten by the arguments if they are present.

### CODE REVIEW

**Comment by davidbiancolin** [comment]
@russell-horvath do you know why github isn't showing a diff of the `sh` script? It just says it was deleted and a new file was added. I'm going to look at it from my terminal instead.

**Comment by russell-horvath** [comment]
> @russell-horvath do you know why github isn't showing a diff of the `sh` script? It just says it was deleted and a new file was added. I'm going to look at it from my terminal instead.

Yeah because it was a symlink to a script in the `examples` directory I had to unlink it and create a 'new' file.

**Comment by russell-horvath** [comment]
> Blindly pulling in a new version of aws-fpga might produce conflicts in the shell script that will go unnoticed.

With that being said though this script was last modified 13 months ago so it may just have to be something kept in mind during review if there are ever any changes (for now). Are there any documentation for bumping the shell_stable version? Maybe we can put a note there?

**Review by davidbiancolin — APPROVED** [review]

**Comment by sagark** [comment]
Please hold off on merging this for a bit, unless you're okay with it being in a point release.

**Pull request merged**
